baseURL = 'https://pale-bluedot.github.io/mindful-queries/'
languageCode = 'en-us'
theme = "hugo-theme-console"
title = 'mindful queries'

[params]
# Cutting off the page title to two chars for mobile (console-demo -> co)
titleCutting = false

[[params.navlinks]]
name = "about/"
url = "about/"

[[params.navlinks]]
name = "posts/"
url = "posts/"
